# Generated by Django 5.2.4 on 2025-08-13 16:25

import django.db.models.deletion
import stressdetector.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressdetector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inhale_time', models.IntegerField(help_text='Inhale duration in seconds')),
                ('hold_time', models.IntegerField(help_text='Hold breath duration in seconds')),
                ('exhale_time', models.IntegerField(help_text='Exhale duration in seconds')),
                ('cycles', models.IntegerField(default=5, help_text='Number of breathing cycles')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Breathing Exercise',
                'verbose_name_plural': 'Breathing Exercises',
            },
        ),
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='General', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivational Quote',
                'verbose_name_plural': 'Motivational Quotes',
            },
        ),
        migrations.CreateModel(
            name='StressTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('stress_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('All', 'All')], default='All', max_length=10)),
                ('category', models.CharField(default='General', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stress Tip',
                'verbose_name_plural': 'Stress Tips',
                'ordering': ['stress_level', 'category'],
            },
        ),
        migrations.AlterModelOptions(
            name='stressprediction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stress Prediction', 'verbose_name_plural': 'Stress Predictions'},
        ),
        migrations.RemoveField(
            model_name='stressprediction',
            name='mood',
        ),
        migrations.AddField(
            model_name='stressprediction',
            name='mood_tag',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad')], default='Neutral', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stressprediction',
            name='confidence',
            field=models.IntegerField(help_text='Confidence percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='stressprediction',
            name='image',
            field=models.ImageField(upload_to=stressdetector.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='stressprediction',
            name='stress_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stressprediction',
            name='stress_type',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Social', 'Social'), ('Health', 'Health'), ('Financial', 'Financial'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='MoodJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=stressdetector.models.get_journal_image_path)),
                ('text_sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], max_length=10)),
                ('image_stress_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('combined_stress_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('stress_keywords', models.JSONField(blank=True, default=list, help_text='List of stress-related keywords found in text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Journal',
                'verbose_name_plural': 'Mood Journals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StressComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to=stressdetector.models.get_comparison_image_path)),
                ('after_image', models.ImageField(upload_to=stressdetector.models.get_comparison_image_path)),
                ('before_stress_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('after_stress_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('before_confidence', models.IntegerField()),
                ('after_confidence', models.IntegerField()),
                ('improvement_score', models.IntegerField(help_text='Percentage improvement (can be negative)')),
                ('comparison_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stress Comparison',
                'verbose_name_plural': 'Stress Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_state', models.CharField(choices=[('happy', 'Happy 😄'), ('neutral', 'Neutral 😐'), ('stressed', 'Stressed 😣'), ('sleeping', 'Sleeping 😴')], default='neutral', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('streak_days', models.IntegerField(default=0)),
                ('total_predictions', models.IntegerField(default=0)),
                ('total_journal_entries', models.IntegerField(default=0)),
                ('total_comparisons', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('pages_visited', models.IntegerField(default=0)),
                ('predictions_made', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_count', models.IntegerField(default=0)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Streak',
                'verbose_name_plural': 'Daily Streaks',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
